name: Publish package
on:
  release:
    types: [released, prereleased, published, created, edited]
    tags:
      - v*
  
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      #- name: Set up Java for publishing to Maven Central Repository
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'
      #    distribution: 'adopt'
      #    server-id: ossrh
      #    server-username: MAVEN_USERNAME
      #    server-password: MAVEN_PASSWORD
      #- name: Publish to the Maven Central Repository
      #  run: mvn --batch-mode deploy
      #  env:
      #    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      #- name: Set up Java for publishing to GitHub Packages
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'
      #    distribution: 'adopt'
      #- name: Publish to GitHub Packages
      #  run: mvn --batch-mode deploy -s $GITHUB_WORKSPACE/settings.xml
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
